source 'http://gemcutter.org'

gem 'andand',             '=1.3.1'
gem 'awesome_print',      '=0.2.1',  :require => 'ap'
gem 'authlogic',          '=2.1.6'
gem 'bundler',            '=1.0.0'
gem 'capistrano',         '=2.5.19'
gem 'compass',            '=0.8.17'
gem 'exceptional',        '=2.0.6'
gem 'haml',               '=3.0.18'
gem 'highline',           '=1.5.2'
gem 'mysql',              '=2.8.1'
gem 'rack',               '=1.0.1'
gem 'rails',              '=2.3.5'
gem 'pwfoo',              '=0.1.2'

group :development, :test, :cucumber, :culerity do
  gem 'factory_girl',     '=1.3.2'  
  gem 'heroku_san',       '=0.2.4'
  gem 'query_diet',       '=0.2.0'
  gem 'ruby-debug',       '=0.10.3'
end

group :test, :cucumber, :culerity do
  gem 'assertions',       '=1.6.0',  :require => nil, :git => "git://github.com/expectedbehavior/assertions.git"
  gem 'capybara',         '=0.3.9'      
  gem 'celerity',         '=0.8.1',  :require => nil
  gem 'culerity',         '=0.2.4',  :require => nil
  gem 'cucumber',         '=0.8.5'
  gem 'cucumber-rails',   '=0.3.2'
  gem 'database_cleaner', '=0.5.2',  :require => nil
  gem 'redgreen',         '=1.2.2',  :require => nil
  gem 'rspec',            '=1.3.0',  :require => nil
  gem 'rspec-rails',      '=1.3.2',  :require => nil
end
