source :rubygems

gem 'andand',             '=1.3.1'  # 
gem 'awesome_print',      '~>0.4.0' # 
gem 'authlogic',          '=3.0.3'  # 
gem 'bundler',            '~>1.0.0' # 
gem 'capistrano',         '=2.6.0'  # 2.6.0
gem 'compass',            '=0.11.3' # 0.11.3
gem 'email_veracity',     '=0.6.0'  # 
gem 'exceptional',        '=2.0.6'  # 2.0.32 
gem 'haml',               '=3.1.2'  # 3.1.2
gem 'sass',               '=3.1.3'
gem 'highline',           '=1.5.2'  # 1.6.2
gem 'html5-boilerplate',  '=1.0.0'  # 1.0.0
#gem 'mysql',              '=2.8.1'  # 
gem 'mysql2',             '=0.3.6'  # 
gem 'pwfoo',              '=0.1.2'  # 
gem 'rack',               '=1.2.1'  # 
gem 'rails',              '=3.0.9'  # 
gem 'rake',               '=0.9.2'  # 0.9.2
gem 'will_paginate',      '=2.3.15' # 

group :development, :test, :cucumber, :culerity do
  gem 'cf_ruby_gems',     '=0.1.9', :require => nil
  gem 'factory_girl',     '=1.3.3'  # 1.3.3 
  gem 'ghost',            '=0.2.8'  #  
  gem 'haml_scaffold',    '=1.1.0'  # 
  gem 'heroku',           '=2.3.6'  # 2.3.6
  gem 'heroku_san',       '=1.2.2'  # 1.2.2
  gem 'mocha',            '=0.9.12' # 0.9.12
#  gem 'query_diet',       '=0.2.2'  # 0.2.2
  gem 'ruby-debug',       '=0.10.4' # 0.10.4
  gem 'web_server_config_generator', '=0.1.3', :require => nil
end

group :test, :cucumber, :culerity do
  gem 'assertions',       '=1.6.0',  :require => nil, :git => "git://github.com/expectedbehavior/assertions.git"
  gem 'capybara',         '=1.0.0'                   # 1.0.0
  gem 'celerity',         '=0.8.9',  :require => nil # 0.8.9
  gem 'culerity',         '=0.2.15', :require => nil # 0.2.15
  gem 'cucumber',         '=1.0.0'                   # 1.0.0
  gem 'cucumber-rails',   '=1.0.2'                   # 1.0.2
  gem 'database_cleaner', '=0.6.7',  :require => nil # 0.6.7
  gem 'redgreen',         '=1.2.2',  :require => nil # 
  gem 'rcov',             '=0.9.9'                   # 
  gem 'rspec',            '=2.6.0',  :require => nil # 2.6.0
  gem 'rspec-rails',      '=2.6.1',  :require => nil # 2.6.1
  gem 'turn',             '~>0.8'                    # 0.8.2
end
